name: Run Moonstream DAO tests

on:
  push:
    branches:
      - cicd
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: pip install -U pip
      - name: Install dev dependencies
        run: pip install -e .[dev]
      - name: Black syntax check
        run: black --check moonworm/
      - name: Run unit tests
        run: sh test.sh
